# Generated by Django 5.1.4 on 2025-04-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favourite',
            name='poster',
            field=models.URLField(blank=True, null=True),
        ),
    ]
