# Generated by Django 5.1.4 on 2025-04-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_favourite_unique_together_favourite_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
