# Generated by Django 5.1.4 on 2025-04-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_favourite_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='movie_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
